/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/ghost_w_tophat.glb -o src/Components/CharacterModel.jsx -r public -k 
Author: Noby Grand (https://sketchfab.com/NobyGrand)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ghost-w-tophat-6b1217e3462440519a2d0e3e75bf16d3
Title: Ghost w/ Tophat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CharacterModel(props) {
  const { nodes, materials } = useGLTF('/ghost_w_tophat.glb')
  return (
    <group {...props} dispose={null}>
      <group  scale={0.0034} position={[0,-0.45,0]}>
        <group name="Eyes" position={[0, 155.777, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh name="Eyes_Eyes_0"  receiveShadow geometry={nodes.Eyes_Eyes_0.geometry} material={materials.Eyes} />
          <mesh name="Eyes_Ghost_White_0" receiveShadow geometry={nodes.Eyes_Ghost_White_0.geometry} material={materials.Ghost_White} />
        </group>
        <mesh name="Body_Ghost_White_0" geometry={nodes.Body_Ghost_White_0.geometry} material={materials.Ghost_White} position={[0, 155.777, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} castShadow receiveShadow />
        <mesh name="Hat_Hat_Black_0" geometry={nodes.Hat_Hat_Black_0.geometry} material={materials.Hat_Black} position={[0, 299.13, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} castShadow receiveShadow />
        <mesh name="Rim_Rim_Red_0" geometry={nodes.Rim_Rim_Red_0.geometry} material={materials.Rim_Red} position={[0, 235.411, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} castShadow receiveShadow />
      </group>
    </group>
  )
}

useGLTF.preload('/ghost_w_tophat.glb')
