/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx public/fantasy_game_inn.glb -o src/Components/Map.jsx -r public -k 
Author: sirsaugsage (https://sketchfab.com/sirsausage)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-game-inn-192bf30a7e28425ab385aef19769d4b0
Title: Fantasy Game Inn
*/

// npx gltfjsx public/metafactory_booth.glb -o src/Components/Map4.jsx -r public -k 

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { useConfigurator } from '../contexts/Configurator';
import { GLTFLoader } from 'three-stdlib';

export function Map(props) {
  const { nodes, materials } = useGLTF('/fantasy_game_inn.glb')


  const loader = new GLTFLoader();
  const { loading, setLoading } = useConfigurator();

  useEffect(()=>{
    loader.load(
      "/fantasy_game_inn.glb",
      ( gltf ) => {
        
          setLoading(true)
         
      },
      ( xhr ) => {
       
          // called while loading is progressing
          console.log( `${( xhr.loaded / xhr.total * 100 )}% loaded` );
      },
      ( error ) => {
   
          // called when loading has errors
          console.error( 'An error happened', error );
      },
      );

     
  });
  useEffect(()=>{
    // console.log(nodes)
    // nodes.scene.traverse((child)=>{
    //     if(child.isMesh){
    //         child.castShadow = true;
    //         child.receiveShadow =true;
    //     }
    // })
})

  return (
    <RigidBody type="fixed"  colliders="trimesh">
    <group {...props} dispose={null} position={[0,0,0]} name='ground'  receiveShadow>
      <group name="Sketchfab_model" receiveShadow rotation={[-Math.PI / 2, 0, 0]} scale={0.11}>
        <group name="TheInn" receiveShadow position={[0, 0, 0]} >
          <mesh name="TheInn_bakeInn_0" receiveShadow castShadow geometry={nodes.TheInn_bakeInn_0.geometry} material={materials.bakeInn} position={[0.299, 0.463, -1.38]} />
        </group>
      </group>
    </group>
    </RigidBody>
  
  )
}

useGLTF.preload('/fantasy_game_inn.glb')
