/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/vr_apartment.glb -o src/Components/Map3.jsx -r public -k 
Author: FDU_oficial (https://sketchfab.com/FDU_oficial)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vr-apartment-fb1b717d457540129c6bf45315aa2612
Title: VR Apartment
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { GLTFLoader } from 'three-stdlib';
import { useConfigurator } from '../contexts/Configurator';


export function Map3(props) {
  useConfigurator
  const { nodes, materials } = useGLTF('/vr_apartment.glb')
  const loader = new GLTFLoader();
  const { loading, setLoading } = useConfigurator();

  useEffect(()=>{
    loader.load(
      "/vr_apartment.glb",
      ( gltf ) => {
        
          setLoading(true)
         
      },
      ( xhr ) => {
       
          // called while loading is progressing
          console.log( `${( xhr.loaded / xhr.total * 100 )}% loaded` );
      },
      ( error ) => {
   
          // called when loading has errors
          console.error( 'An error happened', error );
      },
      );
  });

  return (
    <RigidBody type="fixed"  colliders="trimesh">
    <group {...props} dispose={null} >
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={2.99}>
        <group name="Circle000" position={[-0.03, -1.565, 0.158]} scale={0.074}>
          <mesh name="Circle000_0" geometry={nodes.Circle000_0.geometry} material={materials.lamp} />
          <mesh name="Circle000_1" geometry={nodes.Circle000_1.geometry} material={materials.ALTAVOZ} />
          <mesh name="Circle000_2" geometry={nodes.Circle000_2.geometry} material={materials['mesa.006']} />
          <mesh name="Circle000_3" geometry={nodes.Circle000_3.geometry} material={materials['GLOSS.001']} />
          <mesh name="Circle000_4" geometry={nodes.Circle000_4.geometry} material={materials.screen} />
        </group>
        <group name="Cube320" position={[-0.942, -0.051, 0.629]} scale={0.017}>
          <mesh name="Cube320_0" geometry={nodes.Cube320_0.geometry} material={materials.UPGLAS} />
          <mesh name="Cube320_1" geometry={nodes.Cube320_1.geometry} material={materials.material} />
          <mesh name="Cube320_2" geometry={nodes.Cube320_2.geometry} material={materials['pomo.001']} />
        </group>
        <group name="Cube008" position={[0.045, -0.842, -0.294]} scale={0.037}>
          <mesh name="Cube008_0" geometry={nodes.Cube008_0.geometry} material={materials.sofa1} />
          <mesh name="Cube008_1" geometry={nodes.Cube008_1.geometry} material={materials.sofa2} />
        </group>
        <group name="Cylinder010" position={[-0.837, -0.728, -0.311]} scale={1.265}>
          <mesh name="Cylinder010_0" geometry={nodes.Cylinder010_0.geometry} material={materials.MARMOL} />
          <mesh name="Cylinder010_1" geometry={nodes.Cylinder010_1.geometry} material={materials['MATE.001']} />
          <mesh name="Cylinder010_2" geometry={nodes.Cylinder010_2.geometry} material={materials.METAL} />
          <mesh name="Cylinder010_3" geometry={nodes.Cylinder010_3.geometry} material={materials.COCINA_BRILLO} />
        </group>
        <group name="Cube021" position={[-2.557, 0.724, 1.039]} rotation={[0, 0, -Math.PI / 2]} scale={0.164}>
          <mesh name="Cube021_0" geometry={nodes.Cube021_0.geometry} material={materials.CERAMIC} />
          <mesh name="Cube021_1" geometry={nodes.Cube021_1.geometry} material={materials.mirror} />
          <mesh name="Cube021_2" geometry={nodes.Cube021_2.geometry} material={materials.grifo_up} />
          <mesh name="Cube021_3" geometry={nodes.Cube021_3.geometry} material={materials.up_bathroom_mate} />
        </group>
        <group name="Cylinder005" position={[1.007, 0.354, 0.629]} scale={0.045}>
          <mesh name="Cylinder005_0" geometry={nodes.Cylinder005_0.geometry} material={materials.ESQUINA_SHINE} />
          <mesh name="Cylinder005_1" geometry={nodes.Cylinder005_1.geometry} material={materials.pantallas} />
          <mesh name="Cylinder005_2" geometry={nodes.Cylinder005_2.geometry} material={materials.MATE} />
        </group>
        <group name="Cube035" position={[-0.525, 0.244, 0.846]} rotation={[2.605, -0.342, -0.691]} scale={[-0.039, 0.038, 0.04]}>
          <mesh name="Cube035_0" geometry={nodes.Cube035_0.geometry} material={materials.GLOSS} />
          <mesh name="Cube035_1" geometry={nodes.Cube035_1.geometry} material={materials.MATE_BILLAR} />
        </group>
        <group name="Cube049" position={[-2.408, -1.405, -0.074]} scale={[0.174, 0.207, 0.207]}>
          <mesh name="Cube049_0" geometry={nodes.Cube049_0.geometry} material={materials.cajon_mesita} />
          <mesh name="Cube049_1" geometry={nodes.Cube049_1.geometry} material={materials.POMOS_CAJON} />
          <mesh name="Cube049_2" geometry={nodes.Cube049_2.geometry} material={materials.nevera_tx} />
        </group>
        <group name="Cube011" position={[-0.583, 1.397, 0.413]} rotation={[0, 0, -Math.PI / 2]} scale={[0.278, 0.406, 0.406]}>
          <mesh name="Cube011_0" geometry={nodes.Cube011_0.geometry} material={materials.pilar1} />
          <mesh name="Cube011_1" geometry={nodes.Cube011_1.geometry} material={materials.stairs} />
          <mesh name="Cube011_2" geometry={nodes.Cube011_2.geometry} material={materials.pilar2} />
        </group>
        <group name="Cylinder044" position={[-3.835, -0.751, 0.061]} rotation={[-1.575, 1.551, -3.14]} scale={[0.016, 0.016, 0.048]}>
          <mesh name="Cylinder044_0" geometry={nodes.Cylinder044_0.geometry} material={materials.shine} />
          <mesh name="Cylinder044_1" geometry={nodes.Cylinder044_1.geometry} material={materials.puerta} />
          <mesh name="Cylinder044_2" geometry={nodes.Cylinder044_2.geometry} material={materials.lower_dors} />
          <mesh name="Cylinder044_3" geometry={nodes.Cylinder044_3.geometry} material={materials.espejo} />
        </group>
        <group name="MOAR_SABINE001" position={[-2.959, -1.694, 1.066]} rotation={[Math.PI / 2, 0, 0]} scale={0.364}>
          <mesh name="MOAR_SABINE001_0" geometry={nodes.MOAR_SABINE001_0.geometry} material={materials.border} />
          <mesh name="MOAR_SABINE001_1" geometry={nodes.MOAR_SABINE001_1.geometry} material={materials.bedroom_screen} />
          <mesh name="MOAR_SABINE001_2" geometry={nodes.MOAR_SABINE001_2.geometry} material={materials.CAJONES} />
          <mesh name="MOAR_SABINE001_3" geometry={nodes.MOAR_SABINE001_3.geometry} material={materials.BEDROOM_MATE} />
        </group>
        <group name="Cube001" position={[-2.93, 0.976, -0.107]} rotation={[0, 0, Math.PI / 2]} scale={0.061}>
          <mesh name="Cube001_0" geometry={nodes.Cube001_0.geometry} material={materials.ceramic} />
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.grifo} />
          <mesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.TAPON} />
        </group>
        <group name="Cube002" position={[-0.525, 0.244, 0.846]} rotation={[2.605, -0.342, -0.691]} scale={[-0.039, 0.038, 0.04]}>
          <mesh name="Cube002_0" geometry={nodes.Cube002_0.geometry} material={materials.mate} />
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials.metal_gloss} />
        </group>
        <group name="Cube003" position={[-2.672, -0.213, 0.565]} scale={0.084}>
          <mesh name="Cube003_0" geometry={nodes.Cube003_0.geometry} material={materials.ceiling1} />
          <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials.ceiling2} />
        </group>
        <mesh name="Cube004_0" geometry={nodes.Cube004_0.geometry} material={materials.WINDOWS} position={[1.505, -1.375, -0.294]} scale={0.175} />
        <mesh name="Cube013_0" geometry={nodes.Cube013_0.geometry} material={materials['shower.002']} position={[-2.837, 0.861, 1.066]} rotation={[0, 0, -Math.PI / 2]} scale={0.164} />
        <mesh name="^0A6FB32C8DC72FF21F137A84B2B04C22FA8228053090CCF372^pimgpsh_ful_0" geometry={nodes['^0A6FB32C8DC72FF21F137A84B2B04C22FA8228053090CCF372^pimgpsh_ful_0'].geometry} material={materials.floor1} position={[-0.425, -0.534, -0.303]} scale={4.209} />
        <mesh name="Cylinder038_0" geometry={nodes.Cylinder038_0.geometry} material={materials.material} position={[-3.32, -0.169, 0.263]} scale={[0.011, 0.011, 0.028]} />
        <mesh name="Cube036_0" geometry={nodes.Cube036_0.geometry} material={materials.PREVIEW} position={[-1.851, -1.649, 1.503]} scale={[1, 1.089, 1]} />
        <mesh name="Cube006_0" geometry={nodes.Cube006_0.geometry} material={materials.walls} position={[2.39, -2.416, -0.225]} scale={[0.104, 0.011, 0.118]} />
        <mesh name="Cube012_0" geometry={nodes.Cube012_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube027_0" geometry={nodes.Cube027_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube041_0" geometry={nodes.Cube041_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube066_0" geometry={nodes.Cube066_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube067_0" geometry={nodes.Cube067_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube068_0" geometry={nodes.Cube068_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube069_0" geometry={nodes.Cube069_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube070_0" geometry={nodes.Cube070_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube071_0" geometry={nodes.Cube071_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube072_0" geometry={nodes.Cube072_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube073_0" geometry={nodes.Cube073_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube074_0" geometry={nodes.Cube074_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube075_0" geometry={nodes.Cube075_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube077_0" geometry={nodes.Cube077_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube078_0" geometry={nodes.Cube078_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube079_0" geometry={nodes.Cube079_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube080_0" geometry={nodes.Cube080_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube081_0" geometry={nodes.Cube081_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube082_0" geometry={nodes.Cube082_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube083_0" geometry={nodes.Cube083_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube084_0" geometry={nodes.Cube084_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube085_0" geometry={nodes.Cube085_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube086_0" geometry={nodes.Cube086_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube087_0" geometry={nodes.Cube087_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube088_0" geometry={nodes.Cube088_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube089_0" geometry={nodes.Cube089_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube090_0" geometry={nodes.Cube090_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube091_0" geometry={nodes.Cube091_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube092_0" geometry={nodes.Cube092_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube093_0" geometry={nodes.Cube093_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube094_0" geometry={nodes.Cube094_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube097_0" geometry={nodes.Cube097_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube098_0" geometry={nodes.Cube098_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube099_0" geometry={nodes.Cube099_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube100_0" geometry={nodes.Cube100_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube101_0" geometry={nodes.Cube101_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube102_0" geometry={nodes.Cube102_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube103_0" geometry={nodes.Cube103_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube104_0" geometry={nodes.Cube104_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube107_0" geometry={nodes.Cube107_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube108_0" geometry={nodes.Cube108_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube109_0" geometry={nodes.Cube109_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube110_0" geometry={nodes.Cube110_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube111_0" geometry={nodes.Cube111_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube112_0" geometry={nodes.Cube112_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube113_0" geometry={nodes.Cube113_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube114_0" geometry={nodes.Cube114_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube117_0" geometry={nodes.Cube117_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube118_0" geometry={nodes.Cube118_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube119_0" geometry={nodes.Cube119_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube120_0" geometry={nodes.Cube120_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube122_0" geometry={nodes.Cube122_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube123_0" geometry={nodes.Cube123_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube124_0" geometry={nodes.Cube124_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube127_0" geometry={nodes.Cube127_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube128_0" geometry={nodes.Cube128_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube129_0" geometry={nodes.Cube129_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube130_0" geometry={nodes.Cube130_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube131_0" geometry={nodes.Cube131_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube132_0" geometry={nodes.Cube132_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube133_0" geometry={nodes.Cube133_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube134_0" geometry={nodes.Cube134_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube137_0" geometry={nodes.Cube137_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube138_0" geometry={nodes.Cube138_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube139_0" geometry={nodes.Cube139_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube140_0" geometry={nodes.Cube140_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube141_0" geometry={nodes.Cube141_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube143_0" geometry={nodes.Cube143_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube144_0" geometry={nodes.Cube144_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube147_0" geometry={nodes.Cube147_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube148_0" geometry={nodes.Cube148_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube149_0" geometry={nodes.Cube149_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube150_0" geometry={nodes.Cube150_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube151_0" geometry={nodes.Cube151_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube153_0" geometry={nodes.Cube153_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube154_0" geometry={nodes.Cube154_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube155_0" geometry={nodes.Cube155_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube157_0" geometry={nodes.Cube157_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube158_0" geometry={nodes.Cube158_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube159_0" geometry={nodes.Cube159_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube160_0" geometry={nodes.Cube160_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube161_0" geometry={nodes.Cube161_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube162_0" geometry={nodes.Cube162_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube163_0" geometry={nodes.Cube163_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube164_0" geometry={nodes.Cube164_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube167_0" geometry={nodes.Cube167_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube168_0" geometry={nodes.Cube168_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube169_0" geometry={nodes.Cube169_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube170_0" geometry={nodes.Cube170_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube171_0" geometry={nodes.Cube171_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube172_0" geometry={nodes.Cube172_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube173_0" geometry={nodes.Cube173_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube174_0" geometry={nodes.Cube174_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube175_0" geometry={nodes.Cube175_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube177_0" geometry={nodes.Cube177_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube178_0" geometry={nodes.Cube178_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube179_0" geometry={nodes.Cube179_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube180_0" geometry={nodes.Cube180_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube181_0" geometry={nodes.Cube181_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube183_0" geometry={nodes.Cube183_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube184_0" geometry={nodes.Cube184_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube187_0" geometry={nodes.Cube187_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube188_0" geometry={nodes.Cube188_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube189_0" geometry={nodes.Cube189_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube191_0" geometry={nodes.Cube191_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube193_0" geometry={nodes.Cube193_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube194_0" geometry={nodes.Cube194_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube197_0" geometry={nodes.Cube197_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube198_0" geometry={nodes.Cube198_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube199_0" geometry={nodes.Cube199_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube200_0" geometry={nodes.Cube200_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube201_0" geometry={nodes.Cube201_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube203_0" geometry={nodes.Cube203_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube204_0" geometry={nodes.Cube204_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube207_0" geometry={nodes.Cube207_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube208_0" geometry={nodes.Cube208_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube209_0" geometry={nodes.Cube209_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube211_0" geometry={nodes.Cube211_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube213_0" geometry={nodes.Cube213_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube215_0" geometry={nodes.Cube215_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube216_0" geometry={nodes.Cube216_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube217_0" geometry={nodes.Cube217_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube219_0" geometry={nodes.Cube219_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube221_0" geometry={nodes.Cube221_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube222_0" geometry={nodes.Cube222_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube223_0" geometry={nodes.Cube223_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube224_0" geometry={nodes.Cube224_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube225_0" geometry={nodes.Cube225_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube227_0" geometry={nodes.Cube227_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube228_0" geometry={nodes.Cube228_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube229_0" geometry={nodes.Cube229_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube230_0" geometry={nodes.Cube230_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube231_0" geometry={nodes.Cube231_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube232_0" geometry={nodes.Cube232_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube233_0" geometry={nodes.Cube233_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube234_0" geometry={nodes.Cube234_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube237_0" geometry={nodes.Cube237_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube238_0" geometry={nodes.Cube238_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube239_0" geometry={nodes.Cube239_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube241_0" geometry={nodes.Cube241_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube243_0" geometry={nodes.Cube243_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube246_0" geometry={nodes.Cube246_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube247_0" geometry={nodes.Cube247_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube248_0" geometry={nodes.Cube248_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube249_0" geometry={nodes.Cube249_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube250_0" geometry={nodes.Cube250_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube251_0" geometry={nodes.Cube251_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube252_0" geometry={nodes.Cube252_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube253_0" geometry={nodes.Cube253_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube254_0" geometry={nodes.Cube254_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube255_0" geometry={nodes.Cube255_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube257_0" geometry={nodes.Cube257_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube258_0" geometry={nodes.Cube258_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube259_0" geometry={nodes.Cube259_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube260_0" geometry={nodes.Cube260_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube261_0" geometry={nodes.Cube261_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube262_0" geometry={nodes.Cube262_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube263_0" geometry={nodes.Cube263_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube264_0" geometry={nodes.Cube264_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube265_0" geometry={nodes.Cube265_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube267_0" geometry={nodes.Cube267_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube268_0" geometry={nodes.Cube268_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube269_0" geometry={nodes.Cube269_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Cube271_0" geometry={nodes.Cube271_0.geometry} material={materials.city} position={[-5.477, -5.551, -4.703]} scale={0.783} />
        <mesh name="Plane001_0" geometry={nodes.Plane001_0.geometry} material={materials.city} position={[2.878, -4.735, -4.624]} rotation={[-Math.PI, 0, 0]} scale={[-60.489, 60.489, 60.489]} />
        <mesh name="Cube018_0" geometry={nodes.Cube018_0.geometry} material={materials.city} position={[13.372, 18.729, -4.703]} scale={0.783} />
        <mesh name="Cube272_0" geometry={nodes.Cube272_0.geometry} material={materials.city} position={[13.372, 18.729, -4.703]} scale={0.783} />
        <mesh name="Cube273_0" geometry={nodes.Cube273_0.geometry} material={materials.city} position={[13.372, 18.729, -4.703]} scale={0.783} />
        <mesh name="Cube274_0" geometry={nodes.Cube274_0.geometry} material={materials.city} position={[13.372, 18.729, -4.703]} scale={0.783} />
        <mesh name="Cube275_0" geometry={nodes.Cube275_0.geometry} material={materials.city} position={[13.372, 18.729, -4.703]} scale={0.783} />
        <mesh name="Cube276_0" geometry={nodes.Cube276_0.geometry} material={materials.city} position={[13.372, 18.729, -4.703]} scale={0.783} />
        <mesh name="Cube277_0" geometry={nodes.Cube277_0.geometry} material={materials.city} position={[1.403, 20.199, -4.703]} scale={0.783} />
        <mesh name="Cube278_0" geometry={nodes.Cube278_0.geometry} material={materials.city} position={[1.403, 20.199, -4.703]} scale={0.783} />
        <mesh name="Cube279_0" geometry={nodes.Cube279_0.geometry} material={materials.city} position={[1.403, 20.199, -4.703]} scale={0.783} />
        <mesh name="Cube280_0" geometry={nodes.Cube280_0.geometry} material={materials.city} position={[1.403, 20.199, -4.703]} scale={0.783} />
        <mesh name="Cube281_0" geometry={nodes.Cube281_0.geometry} material={materials.city} position={[1.403, 20.199, -4.703]} scale={0.783} />
        <mesh name="Cube282_0" geometry={nodes.Cube282_0.geometry} material={materials.city} position={[1.403, 20.199, -4.703]} scale={0.783} />
        <mesh name="Cube283_0" geometry={nodes.Cube283_0.geometry} material={materials.city} position={[22.682, 0.18, -4.702]} scale={0.783} />
        <mesh name="Cube121_0" geometry={nodes.Cube121_0.geometry} material={materials.city} position={[-5.477, -5.551, -7.662]} scale={0.783} />
        <mesh name="Cube285_0" geometry={nodes.Cube285_0.geometry} material={materials.city} position={[22.682, 0.18, -4.702]} scale={0.783} />
        <mesh name="Cube286_0" geometry={nodes.Cube286_0.geometry} material={materials.city} position={[22.682, 0.18, -4.702]} scale={0.783} />
        <mesh name="Cube287_0" geometry={nodes.Cube287_0.geometry} material={materials.city} position={[22.682, 0.18, -4.702]} scale={0.783} />
        <mesh name="Cube288_0" geometry={nodes.Cube288_0.geometry} material={materials.city} position={[22.682, 0.18, -4.702]} scale={0.783} />
        <mesh name="Cube289_0" geometry={nodes.Cube289_0.geometry} material={materials.city} position={[7.843, -17.038, -4.703]} scale={0.783} />
        <mesh name="Cube290_0" geometry={nodes.Cube290_0.geometry} material={materials.city} position={[7.843, -17.038, -4.703]} scale={0.783} />
        <mesh name="Cube291_0" geometry={nodes.Cube291_0.geometry} material={materials.city} position={[7.843, -17.038, -4.703]} scale={0.783} />
        <mesh name="Cube292_0" geometry={nodes.Cube292_0.geometry} material={materials.city} position={[7.843, -17.038, -4.703]} scale={0.783} />
        <mesh name="Cube293_0" geometry={nodes.Cube293_0.geometry} material={materials.city} position={[7.843, -17.038, -4.703]} scale={0.783} />
        <mesh name="Cube294_0" geometry={nodes.Cube294_0.geometry} material={materials.city} position={[7.843, -17.038, -4.703]} scale={0.783} />
        <mesh name="Cube295_0" geometry={nodes.Cube295_0.geometry} material={materials.city} position={[-6.437, -21.588, -4.704]} scale={0.783} />
        <mesh name="Cube296_0" geometry={nodes.Cube296_0.geometry} material={materials.city} position={[-6.437, -21.588, -4.704]} scale={0.783} />
        <mesh name="Cube297_0" geometry={nodes.Cube297_0.geometry} material={materials.city} position={[-6.437, -21.588, -4.704]} scale={0.783} />
        <mesh name="Cube298_0" geometry={nodes.Cube298_0.geometry} material={materials.city} position={[-6.437, -21.588, -4.704]} scale={0.783} />
        <mesh name="Cube299_0" geometry={nodes.Cube299_0.geometry} material={materials.city} position={[-6.437, -21.588, -4.704]} scale={0.783} />
        <mesh name="Cube300_0" geometry={nodes.Cube300_0.geometry} material={materials.city} position={[-6.437, -21.588, -4.704]} scale={0.783} />
        <mesh name="Cube301_0" geometry={nodes.Cube301_0.geometry} material={materials.city} position={[-16.656, -22.568, -4.704]} scale={0.783} />
        <mesh name="Cube302_0" geometry={nodes.Cube302_0.geometry} material={materials.city} position={[-16.656, -22.568, -4.704]} scale={0.783} />
        <mesh name="Cube303_0" geometry={nodes.Cube303_0.geometry} material={materials.city} position={[-16.656, -22.568, -4.704]} scale={0.783} />
        <mesh name="Cube304_0" geometry={nodes.Cube304_0.geometry} material={materials.city} position={[-16.656, -22.568, -4.704]} scale={0.783} />
        <mesh name="Cube305_0" geometry={nodes.Cube305_0.geometry} material={materials.city} position={[-16.656, -22.568, -4.704]} scale={0.783} />
        <mesh name="Cube306_0" geometry={nodes.Cube306_0.geometry} material={materials.city} position={[-16.656, -22.568, -4.704]} scale={0.783} />
        <mesh name="Cube307_0" geometry={nodes.Cube307_0.geometry} material={materials.city} position={[-26.246, -21.308, -4.705]} scale={0.783} />
        <mesh name="Cube308_0" geometry={nodes.Cube308_0.geometry} material={materials.city} position={[-26.246, -21.308, -4.705]} scale={0.783} />
        <mesh name="Cube309_0" geometry={nodes.Cube309_0.geometry} material={materials.city} position={[-26.246, -21.308, -4.705]} scale={0.783} />
        <mesh name="Cube310_0" geometry={nodes.Cube310_0.geometry} material={materials.city} position={[-26.246, -21.308, -4.705]} scale={0.783} />
        <mesh name="Cube311_0" geometry={nodes.Cube311_0.geometry} material={materials.city} position={[-26.246, -21.308, -4.705]} scale={0.783} />
        <mesh name="Cube312_0" geometry={nodes.Cube312_0.geometry} material={materials.city} position={[-26.246, -21.308, -4.705]} scale={0.783} />
        <mesh name="Cube318_0" geometry={nodes.Cube318_0.geometry} material={materials.top_walls} position={[-1.854, -1.782, 0.6]} scale={0.084} />
        <mesh name="Cube321_0" geometry={nodes.Cube321_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube322_0" geometry={nodes.Cube322_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube323_0" geometry={nodes.Cube323_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube324_0" geometry={nodes.Cube324_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube325_0" geometry={nodes.Cube325_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube326_0" geometry={nodes.Cube326_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube327_0" geometry={nodes.Cube327_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube328_0" geometry={nodes.Cube328_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube329_0" geometry={nodes.Cube329_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube330_0" geometry={nodes.Cube330_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube331_0" geometry={nodes.Cube331_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube332_0" geometry={nodes.Cube332_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube333_0" geometry={nodes.Cube333_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube334_0" geometry={nodes.Cube334_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube335_0" geometry={nodes.Cube335_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube336_0" geometry={nodes.Cube336_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube337_0" geometry={nodes.Cube337_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube338_0" geometry={nodes.Cube338_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube339_0" geometry={nodes.Cube339_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube340_0" geometry={nodes.Cube340_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube341_0" geometry={nodes.Cube341_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube342_0" geometry={nodes.Cube342_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube343_0" geometry={nodes.Cube343_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube344_0" geometry={nodes.Cube344_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube345_0" geometry={nodes.Cube345_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube346_0" geometry={nodes.Cube346_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube347_0" geometry={nodes.Cube347_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube348_0" geometry={nodes.Cube348_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube349_0" geometry={nodes.Cube349_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube350_0" geometry={nodes.Cube350_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube351_0" geometry={nodes.Cube351_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube352_0" geometry={nodes.Cube352_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube353_0" geometry={nodes.Cube353_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube284_0" geometry={nodes.Cube284_0.geometry} material={materials.city} position={[22.682, 0.18, -4.702]} scale={0.783} />
        <mesh name="Cube355_0" geometry={nodes.Cube355_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube356_0" geometry={nodes.Cube356_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube357_0" geometry={nodes.Cube357_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube358_0" geometry={nodes.Cube358_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube359_0" geometry={nodes.Cube359_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube360_0" geometry={nodes.Cube360_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube361_0" geometry={nodes.Cube361_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube362_0" geometry={nodes.Cube362_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube363_0" geometry={nodes.Cube363_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube364_0" geometry={nodes.Cube364_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube365_0" geometry={nodes.Cube365_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube366_0" geometry={nodes.Cube366_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube367_0" geometry={nodes.Cube367_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube368_0" geometry={nodes.Cube368_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube369_0" geometry={nodes.Cube369_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube370_0" geometry={nodes.Cube370_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube371_0" geometry={nodes.Cube371_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube378_0" geometry={nodes.Cube378_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube379_0" geometry={nodes.Cube379_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube380_0" geometry={nodes.Cube380_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube381_0" geometry={nodes.Cube381_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube382_0" geometry={nodes.Cube382_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube383_0" geometry={nodes.Cube383_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube462_0" geometry={nodes.Cube462_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube463_0" geometry={nodes.Cube463_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube464_0" geometry={nodes.Cube464_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube465_0" geometry={nodes.Cube465_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube466_0" geometry={nodes.Cube466_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube467_0" geometry={nodes.Cube467_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube468_0" geometry={nodes.Cube468_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube469_0" geometry={nodes.Cube469_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube470_0" geometry={nodes.Cube470_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube354_0" geometry={nodes.Cube354_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube471_0" geometry={nodes.Cube471_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube472_0" geometry={nodes.Cube472_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube473_0" geometry={nodes.Cube473_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube474_0" geometry={nodes.Cube474_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube475_0" geometry={nodes.Cube475_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube476_0" geometry={nodes.Cube476_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube477_0" geometry={nodes.Cube477_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube478_0" geometry={nodes.Cube478_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube480_0" geometry={nodes.Cube480_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube481_0" geometry={nodes.Cube481_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube482_0" geometry={nodes.Cube482_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube483_0" geometry={nodes.Cube483_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube484_0" geometry={nodes.Cube484_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube485_0" geometry={nodes.Cube485_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube486_0" geometry={nodes.Cube486_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube487_0" geometry={nodes.Cube487_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube488_0" geometry={nodes.Cube488_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube489_0" geometry={nodes.Cube489_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="Cube490_0" geometry={nodes.Cube490_0.geometry} material={materials.city} position={[1.263, 3.81, -4.703]} rotation={[0, 0, -Math.PI]} scale={0.783} />
        <mesh name="^0A6FB32C8DC72FF21F137A84B2B04C22FA8228053090CCF372^pimgpsh000_0" geometry={nodes['^0A6FB32C8DC72FF21F137A84B2B04C22FA8228053090CCF372^pimgpsh000_0'].geometry} material={materials.floor2} position={[0.427, -0.172, -0.294]} scale={4.209} />
        <mesh name="^0A6FB32C8DC72FF21F137A84B2B04C22FA8228053090CCF372^pimgpsh001_0" geometry={nodes['^0A6FB32C8DC72FF21F137A84B2B04C22FA8228053090CCF372^pimgpsh001_0'].geometry} material={materials['madera.003']} position={[-0.425, -0.534, -0.303]} scale={4.209} />
        <mesh name="Cube010_0" geometry={nodes.Cube010_0.geometry} material={materials.top_floor1} position={[-1.854, -1.782, 0.6]} scale={0.084} />
        <mesh name="Cube014_0" geometry={nodes.Cube014_0.geometry} material={materials.low_walls} position={[-0.667, -0.534, -0.294]} scale={[4.183, 4.183, 15.489]} />
        <mesh name="Cube015_0" geometry={nodes.Cube015_0.geometry} material={materials.low_walls} position={[-0.667, -0.534, -0.294]} scale={[4.183, 4.183, 15.489]} />
        <mesh name="Cube005_0" geometry={nodes.Cube005_0.geometry} material={materials.top_floor1} position={[-1.854, -1.782, 0.6]} scale={0.084} />
        <mesh name="Cube007_0" geometry={nodes.Cube007_0.geometry} material={materials.top_floor1} position={[-0.62, 1.478, 0.629]} scale={0.084} />
        <mesh name="Cube016_0" geometry={nodes.Cube016_0.geometry} material={materials.top_floor2} position={[-1.854, -1.782, 0.6]} scale={0.084} />
        <mesh name="Cube017_0" geometry={nodes.Cube017_0.geometry} material={materials.top_walls} position={[-1.854, -1.782, 0.6]} scale={0.084} />
        <mesh name="Cube019_0" geometry={nodes.Cube019_0.geometry} material={materials.top_ceiling1} position={[-2.966, -0.163, 1.483]} scale={[1, 1.089, 1]} />
        <mesh name="Cube020_0" geometry={nodes.Cube020_0.geometry} material={materials.top_ceiling2} position={[-0.084, -0.163, 1.483]} scale={[1, 1.089, 1]} />
      </group>
    </group>
    </RigidBody>
  )
}

useGLTF.preload('/vr_apartment.glb')
