/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/metafactory_booth.glb -o src/Components/Map4.jsx -r public -k 
Author: m3org (https://sketchfab.com/m3org)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/metafactory-booth-04cc03493f6349829a9a7cdc88010c5f
Title: MetaFactory booth
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useConfigurator } from "../contexts/Configurator";
import { GLTFLoader } from "three-stdlib";
import { RigidBody } from "@react-three/rapier";

export function Map4(props) {
  const { nodes, materials } = useGLTF("/metafactory_booth.glb");

  const loader = new GLTFLoader();
  const { loading, setLoading } = useConfigurator();

  useEffect(() => {
    loader.load(
      "/metafactory_booth.glb",
      (gltf) => {
        setLoading(true);
      },
      (xhr) => {
        // called while loading is progressing
        console.log(`${(xhr.loaded / xhr.total) * 100}% loaded`);
      },
      (error) => {
        // called when loading has errors
        console.error("An error happened", error);
      },
    );
  });

  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group {...props} dispose={null} position={[0, -2, 0]}>
        <group
          name="Clothes_rack_8"
          position={[0, 1.827, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.024}
        >
          <group
            name="Object_6_7"
            position={[-23.032, 260.432, -5.813]}
            rotation={[0, 0, -3.133]}
            scale={0.604}
          >
            <mesh
              name="Object_14"
              geometry={nodes.Object_14.geometry}
              material={materials.greyPlastic}
            />
            <mesh
              name="Object_15"
              geometry={nodes.Object_15.geometry}
              material={materials.holes}
            />
            <mesh
              name="Object_16"
              geometry={nodes.Object_16.geometry}
              material={materials.whiteMetal}
            />
          </group>
        </group>
        <group
          name="B1_Teal_9"
          position={[3.29, 7.184, 5.46]}
          rotation={[0, -1.54, 0]}
          scale={[0.822, 0.822, 0.009]}
        >
          <mesh
            name="Object_18"
            geometry={nodes.Object_18.geometry}
            material={materials.Teal}
          />
          <mesh
            name="Object_19"
            geometry={nodes.Object_19.geometry}
            material={materials.Face_Outlines}
          />
          <mesh
            name="Object_20"
            geometry={nodes.Object_20.geometry}
            material={materials.Face_Mat}
          />
          <mesh
            name="Object_21"
            geometry={nodes.Object_21.geometry}
            material={materials.material_0}
          />
        </group>
        <group
          name="Sketchfab_model_14"
          position={[16.228, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.526}
        >
          <mesh
            name="Object_27"
            geometry={nodes.Object_27.geometry}
            material={materials["Materiale.002"]}
            position={[-30.794, -0.149, 2.86]}
            scale={[0.698, 0.928, 0.695]}
          />
          <mesh
            name="Object_29"
            geometry={nodes.Object_29.geometry}
            material={materials.aiStandard2SG}
            position={[3.799, 0, 0]}
            scale={[1.735, 1, 1]}
          />
        </group>
        <group
          name="B1_Teal001_15"
          position={[-0.666, 2.041, 4.385]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.211, 0.211, 0.002]}
        >
          <mesh
            name="Object_31"
            geometry={nodes.Object_31.geometry}
            material={materials.Teal}
          />
          <mesh
            name="Object_32"
            geometry={nodes.Object_32.geometry}
            material={materials.Face_Outlines}
          />
          <mesh
            name="Object_33"
            geometry={nodes.Object_33.geometry}
            material={materials.Face_Mat}
          />
          <mesh
            name="Object_34"
            geometry={nodes.Object_34.geometry}
            material={materials.material_0}
          />
        </group>
        <group
          name="Cube001_26"
          position={[-2.906, 1.746, -3.9]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.445, 0.325, 0.877]}
        >
          <mesh
            name="Object_56"
            geometry={nodes.Object_56.geometry}
            material={materials.Materiale}
          />
          <mesh
            name="Object_57"
            geometry={nodes.Object_57.geometry}
            material={materials["Materiale.004"]}
          />
        </group>
        <group
          name="Cube002_30"
          position={[-2.91, 1.746, -5.816]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.445, 0.325, 0.877]}
        >
          <mesh
            name="Object_59"
            geometry={nodes.Object_59.geometry}
            material={materials.Materiale}
          />
          <mesh
            name="Object_60"
            geometry={nodes.Object_60.geometry}
            material={materials["Materiale.004"]}
          />
        </group>
        <group
          name="Cube003_31"
          position={[1.839, 1.746, -5.816]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.445, 0.325, 0.877]}
        >
          <mesh
            name="Object_62"
            geometry={nodes.Object_62.geometry}
            material={materials.Materiale}
          />
          <mesh
            name="Object_63"
            geometry={nodes.Object_63.geometry}
            material={materials["Materiale.004"]}
          />
        </group>
        {/* <mesh name="Object_7_1" geometry={nodes.Object_7_1.geometry} material={materials.Materiale} rotation={[-Math.PI / 2, 0, 0]} /> */}
        <mesh
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={materials.boothsheet_branding}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Object_23"
          geometry={nodes.Object_23.geometry}
          material={materials["tshirt.003"]}
          position={[-2.483, 2.37, -4.051]}
          scale={0.782}
        />
        <mesh
          name="Object_36"
          geometry={nodes.Object_36.geometry}
          material={materials.material}
          position={[2.273, 2.496, -5.983]}
          rotation={[0.004, -0.32, 0.002]}
          scale={1.22}
        />
        <mesh
          name="Object_38"
          geometry={nodes.Object_38.geometry}
          material={materials.hoodie}
          position={[-3.305, 2.479, -5.865]}
          rotation={[0, 0.096, 0]}
        />
        <mesh
          name="Object_40"
          geometry={nodes.Object_40.geometry}
          material={materials.longsleeve}
          position={[1.427, 2.204, -5.966]}
          rotation={[0, -0.014, 0]}
          scale={1.206}
        />
        <mesh
          name="Object_42"
          geometry={nodes.Object_42.geometry}
          material={materials.Atlas1}
          position={[1.918, 2.477, 6.525]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="Object_44"
          geometry={nodes.Object_44.geometry}
          material={materials.material_0}
          position={[-1.327, 2.54, 4.819]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.012}
        />
        <mesh
          name="Object_46"
          geometry={nodes.Object_46.geometry}
          material={materials.Jacket}
          position={[-0.723, 3.126, 4.932]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.012}
        />
        <mesh
          name="Object_48"
          geometry={nodes.Object_48.geometry}
          material={materials.Materiale}
          position={[-0.685, 3.372, 4.791]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.012}
        />
        <mesh
          name="Object_50"
          geometry={nodes.Object_50.geometry}
          material={materials.tanktop}
          position={[-3.366, 2.367, -4.047]}
          rotation={[-Math.PI, -0.015, -Math.PI]}
        />
        <mesh
          name="Object_52"
          geometry={nodes.Object_52.geometry}
          material={materials.sneakers}
          position={[-2.303, 2.065, -5.932]}
          rotation={[-Math.PI, 0.515, -Math.PI]}
        />
        <mesh
          name="Object_54"
          geometry={nodes.Object_54.geometry}
          material={materials.Material}
          position={[2.28, 2.31, -5.987]}
          rotation={[0, 1.54, 0]}
        />
        <mesh
          name="Object_65"
          geometry={nodes.Object_65.geometry}
          material={materials["Materiale.003"]}
          position={[-2.9, 1.599, -3.896]}
          scale={[0.957, 0.006, 0.529]}
        />
        <mesh
          name="Object_67"
          geometry={nodes.Object_67.geometry}
          material={materials["Materiale.003"]}
          position={[-2.9, 1.599, -5.808]}
          scale={[0.957, 0.006, 0.529]}
        />
        <mesh
          name="Object_69"
          geometry={nodes.Object_69.geometry}
          material={materials["Materiale.003"]}
          position={[1.836, 1.599, -5.808]}
          scale={[0.957, 0.006, 0.529]}
        />
        <mesh
          name="Object_71"
          geometry={nodes.Object_71.geometry}
          material={materials["Materiale.003"]}
          position={[-0.672, 1.599, 4.86]}
          scale={[2.546, 0.006, 0.529]}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload("/metafactory_booth.glb");
